#!/usr/bin/env bash

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, verion 2 ONLY.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ==== Utilities ====
function check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "Root privileges are needed to run operations..."
        exit
    fi
}

function check_prerequisites() {
    packages=("curl" "gnupg2" "ca-certificates" "lsb-release")

    for pkg in ${packages[@]}; do

        is_pkg_installed=$(dpkg-query -W --showformat='${Status}\n' ${pkg} | grep "install ok installed")

        if [ "${is_pkg_installed}" == "install ok installed" ]; then
            echo ${pkg} is installed.
        fi
    done
}

function help() {
    echo "UpVent website CLI tool"
    echo "-----------------------------------"
    echo "Usage:"
    echo "upvnt <option>"
    echo "-----------------------------------"
}

# Main functionalities
