#!/usr/bin/env bash

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, verion 2 ONLY.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ==== Utilities ====

function check_preact() {
    local FILE=UpVent/core/static/core/js/preact.min.js

    if [ -f "$FILE" ]; then
        echo -e "[\e[32mOK\e[39m] $FILE exists."
        read -pr "Do you want to update preact? [Y/n]" ans

        case "$ans" in
            [yY][sS])
                curl -L https://unpkg.com/preact -o preact.min.js && mv preact.min.js $FILE
            ;;
            *)
                echo -e "Update cancelled..."
                exit 0
            ;;
        esac
    else
        echo -e "[\e[31mERROR\e[39m] $FILE does not exist."
        echo -e "[\e[34mINFO\e[39m] Installing the latest preact version..."
        curl -L https://unpkg.com/preact -o preact.min.js && mv preact.min.js $FILE
    fi

}

function check_htm() {
    local FILE=UpVent/core/static/core/js/htm.min.js

    if [ -f "$FILE" ]; then
        echo -e "[\e[32mOK\e[39m] $FILE exists."
        read -pr "Do you want to update htm? [Y/n]" ans

        case "$ans" in
            [yY][sS])
                curl -L https://unpkg.com/htm -o htm.min.js && mv htm.min.js $FILE
            ;;
            *)
                echo -e "Update cancelled..."
                exit 0
            ;;
        esac
    else
        echo -e "[\e[31mERROR\e[39m] $FILE does not exist."
        echo -e "[\e[34mINFO\e[39m] Installing the latest htm version..."
        curl -L https://unpkg.com/htm -o htm.min.js && mv htm.min.js $FILE
    fi

}

function help() {
    echo "UpVent website CLI tool"
    echo "-----------------------------------"
    echo "Usage:"
    echo "upvnt <option>"
    echo "-----------------------------------"
    echo "Options:"
    echo "- preact: Install / Update preact"
    echo "- htm:    Install / Update htm"
    echo "- help:   Show this screen"
}
