# Generated by Django 3.2 on 2021-04-24 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text='Ingrese el nombre de la persona que nos contactó', max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(default='', help_text='Ingrese el apellido de la persona que nos contactó', max_length=50, verbose_name='Apellidos')),
                ('company_name', models.CharField(default='', help_text='Ingrese la compañía o el trabajo de quien nos contactó', max_length=50, verbose_name='Empresa ó Trabajo')),
                ('email', models.EmailField(default='', help_text='Ingrese el correo de la persona que nos contactó', max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(default='', help_text='Ingrese el número de teléfono de la persona que nos contactó', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:        '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de Teléfono')),
                ('reason', models.CharField(default='', help_text='Ingrese la razón de contacto', max_length=100, verbose_name='Razón de Contacto')),
                ('message', models.TextField(default='', help_text='Ingrese el mensaje de contacto', verbose_name='Mensaje de Contacto')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['created_on'],
            },
        ),
    ]
