# Generated by Django 3.2 on 2021-05-04 03:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del post', max_length=200, unique=True, verbose_name='Título')),
                ('image', models.ImageField(help_text='Portada del post. Se recomiendan imágenes rectangulares.', upload_to='posts', verbose_name='Imágen Destacada')),
                ('category', models.CharField(default='None', help_text='Categoría a la que pertenece el post.', max_length=20, verbose_name='Categoría')),
                ('slug', models.SlugField(help_text='Campo autogenerado, no tocar', max_length=200, unique=True, verbose_name='Slug')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Actualizado el: ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Contenido detallado del post', verbose_name='Contenido')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado el: ')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Estatus actual del post')),
                ('side_title', models.CharField(default='Otros Recursos', help_text='Título de la imágen que aparecerá en la parte derecha de        cada post', max_length=200, verbose_name='Título Lateral')),
                ('side_img', models.ImageField(blank=True, help_text='Imágen que aparecera en la parte derecha de cada post.        puede usarse para publicidad u otros fines.', upload_to='posts', verbose_name='Imágen Lateral')),
                ('side_text_title', models.CharField(default='Título del recurso', help_text='Título del texto inferior que aparecerá en la parte derecha        de cada post', max_length=200, verbose_name='Título Lateral')),
                ('site_text', models.TextField(default='Ver más', help_text='Texto mostrado en la parte derecha de cada post, debajo de        la imágen lateral.', verbose_name='Texto Lateral')),
                ('side_button', models.CharField(default='Leer más...', help_text='Texto que mostrará el botón mostrado en la parte derecha        de cada post.', max_length=50, verbose_name='Texto del botón lateral')),
                ('side_button_url', models.URLField(default='https://upvent.codes', help_text='Sitio al que dirigirá el botón lateral mostrado en la parte        derecha de cada post', verbose_name='URL del botón lateral')),
                ('side_video_title', models.CharField(default='Conocer más', help_text='Texto que se mostrará como título del vídeo lateral', max_length=100, verbose_name='Texto del vídeo lateral')),
                ('side_video', models.URLField(default='https://upvent.codes', help_text='URL hacia un vídeo que será mostrado en la parte derecha de        cada post.', verbose_name='Video Lateral')),
                ('author', models.ForeignKey(help_text='Seleccione el autor del post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
        ),
    ]
