# Generated by Django 3.2 on 2021-05-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', help_text='Descripción del post. Usada para mostrarse en motores de        búsqueda y en redes sociales como un texto corto.', max_length=160, verbose_name='Descripción'),
        ),
    ]
