# Generated by Django 3.2.2 on 2021-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='side_img',
            field=models.ImageField(help_text='Imágen que aparecera en la parte derecha de cada post.        puede usarse para publicidad u otros fines.', upload_to='posts', verbose_name='Imágen Lateral'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Campo autogenerado. Modifique de acuerdo a sus necesidades', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
