# Generated by Django 3.2 on 2021-04-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sitio Web'),
        ),
    ]
