# Generated by Django 3.2 on 2021-04-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210409_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='side_button',
            field=models.CharField(default='Leer más...', help_text='Texto que mostrará el botón mostrado en la parte derecha        de cada post.', max_length=50, verbose_name='Texto del botón lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_button_url',
            field=models.URLField(default='https://upvent.codes', help_text='Sitio al que dirigirá el botón lateral mostrado en la parte        derecha de cada post', verbose_name='URL del botón lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_img',
            field=models.ImageField(blank=True, help_text='Imágen que aparecera en la parte derecha de cada post.        puede usarse para publicidad u otros fines.', upload_to='posts', verbose_name='Imágen Lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_title',
            field=models.CharField(default='Otros Recursos', help_text='Título de la imágen que aparecerá en la parte derecha de        cada post', max_length=200, verbose_name='Título Lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_video',
            field=models.URLField(default='https://upvent.codes', help_text='URL hacia un vídeo que será mostrado en la parte derecha de        cada post.', verbose_name='Video Lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_video_title',
            field=models.CharField(default='Conocer más', help_text='Texto que se mostrará como título del vídeo lateral', max_length=100, verbose_name='Texto del vídeo lateral'),
        ),
        migrations.AddField(
            model_name='post',
            name='site_text',
            field=models.TextField(default='Ver más', help_text='Texto mostrado en la parte derecha de cada post, debajo de        la imágen lateral.', verbose_name='Texto Lateral'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Portada del post. Se recomiendan imágenes rectangulares.', upload_to='posts', verbose_name='Imágen Destacada'),
        ),
    ]
