# Generated by Django 3.2 on 2021-04-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210416_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='side_text_title',
            field=models.CharField(default='Título del recurso', help_text='Título del texto inferior que aparecerá en la parte derecha        de cada post', max_length=200, verbose_name='Título Lateral'),
        ),
    ]
