# Generated by Django 3.2 on 2021-05-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210424_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
