from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

# Current blog post status
STATUS = (
    (0, "Draft"),
    (1, "Published")
)

class Post(models.Model):
    # Blog Title
    title = models.CharField(
        verbose_name="Título",
        max_length=200,
        unique=True)

    # Blog portrait
    image = models.ImageField(
        verbose_name="Imágen Destacada",
        upload_to="posts",
        blank=True
    )

    # Blog category
    category = models.CharField(
        verbose_name="Categoría",
        max_length=20,
        default='None'
    )

    # Blog slug (autogenerated)
    slug = models.SlugField(
        verbose_name="Slug",
        max_length=200,
        unique=True
    )

    # Blog author (get from current user)
    author = models.ForeignKey(
        User,
        verbose_name="Autor",
        on_delete= models.CASCADE,related_name='blog_posts'
    )

    # Blog last update date
    updated_on = models.DateTimeField(
        verbose_name="Actualizado el: ",
        auto_now= True
    )

    # Blog content (Handled by CKEditor)
    content = RichTextUploadingField(
        verbose_name="Contenido"
    )

    # Blog creation date
    created_on = models.DateTimeField(
        verbose_name="Creado el: ",
        auto_now_add=True
    )

    # Blog publishing status
    status = models.IntegerField(
        choices=STATUS,
        default=0
    )

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
