# Generated by Django 3.2 on 2021-05-04 03:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Ingrese el nombre del proyecto.', max_length=100, verbose_name='Título')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='floss', verbose_name='Imágen Destacada')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Descripción del proyecto.', verbose_name='Descripción')),
                ('github_addr', models.URLField(default='https://github.com/', help_text='URL completa del repositorio donde se encuentra el proyecto', verbose_name='Dirección de Git')),
                ('support_addr', models.URLField(default='https://github.com/', help_text='URL completa donde los visitantes podrán apoyar al proyecto', verbose_name='Dirección de apoyo')),
                ('plicense', models.CharField(default='', help_text='Ingrese la licencia del proyecto', max_length=25, verbose_name='Licencia')),
                ('license_link', models.URLField(default='https://gnu.org/', help_text='URL completa para ver la licencia del proyecto', verbose_name='URL de licencia')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proyecto de código abierto',
                'verbose_name_plural': 'Proyectos de código abierto',
            },
        ),
        migrations.CreateModel(
            name='HOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gnu Compiler Colection', help_text='Ingrese el nombre del proyecto a mostrar en        el salón de la fama', max_length=60, verbose_name='Nombre')),
                ('icon', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='licenses', verbose_name='Icono del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto del salón de la fama',
                'verbose_name_plural': 'Proyectos del salón de la Fama',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gnu General Public License v2', help_text='Ingrese el nombre de la licencia a mostrar', max_length=60, verbose_name='Nombre')),
                ('verbatim', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Escriba aquí el texto corto o resumen de la licencia', verbose_name='Texto corto de la licencia')),
                ('license_link', models.URLField(default='https://gnu.org/', help_text='URL completa para ver la licencia del proyecto', verbose_name='URL de licencia')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Política de Privacidad', help_text='Ingrese el título para su política de privacidad', max_length=100, verbose_name='Título')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_on', models.DateField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('changelog', models.TextField(help_text='Ingrese la razón de cambiar la política de privacidad.', verbose_name='Registro de Cambios')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Escriba aquí su política de privacidad', verbose_name='Política de privacidad')),
            ],
            options={
                'verbose_name': 'Política de Privacidad',
                'verbose_name_plural': 'Política de Privacidad',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ingrese el nombre del proyecto.', max_length=200, unique=True, verbose_name='Título')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='portfolio', verbose_name='Imágen Destacada')),
                ('site', models.URLField(help_text='El sitio web donde se encuentra alojado el proyecto.', verbose_name='Sitio web')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Descripción del proyecto. Procure ser breve.', verbose_name='Descripción')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='team', verbose_name='Foto del integrante')),
                ('name', models.CharField(default='', help_text='Ingrese el nombre del integrante del equipo', max_length=100, verbose_name='Nombre del Integrante del equipo')),
                ('position', models.CharField(default='', help_text='Ingrese en que ha contribuido o que posición dentro        de UpVent tiene el integrante.', max_length=100, verbose_name='Posición o contribución')),
                ('is_collab', models.BooleanField(default=False, help_text='Indicar si el miembro siendo registrado es un colaborador        externo, de no serlo se tomará como miembro de UpVent', verbose_name='¿Es un colaborador externo?')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes cuadradas', upload_to='testimonials', verbose_name='Foto del cliente')),
                ('name', models.CharField(default='', help_text='Ingrese el nombre de la persona dando su testimonio.', max_length=100, unique=True, verbose_name='Nombre Completo')),
                ('testimonial', ckeditor_uploader.fields.RichTextUploadingField(help_text='Testimonio de la persona.', verbose_name='Testimonio')),
                ('workplace', models.CharField(help_text='Ingrese el puesto que desempeña la persona que da el        testimonio.', max_length=80, verbose_name='Lugar de Trabajo')),
                ('site', models.URLField(help_text='El sitio web donde se encuentra alojado el proyecto.', verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
