# Generated by Django 3.2 on 2021-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.URLField(verbose_name='Sitio web'),
        ),
    ]
