# Generated by Django 3.2 on 2021-04-18 01:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0006_alter_privacypolicy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Ingrese el nombre del proyecto.', max_length=100, verbose_name='Título')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='floss', verbose_name='Imágen Destacada')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Descripción del proyecto.', verbose_name='Descripción')),
                ('github_addr', models.URLField(default='https://github.com/', help_text='URL completa del repositorio donde se encuentra el proyecto', verbose_name='Dirección de Git')),
                ('support_addr', models.URLField(default='https://github.com/', help_text='URL completa donde los visitantes podrán apoyar al proyecto', verbose_name='Dirección de apoyo')),
                ('plicense', models.CharField(default='', help_text='Ingrese la licencia del proyecto', max_length=25, verbose_name='Licencia')),
                ('license_link', models.URLField(default='https://gnu.org/', help_text='URL completa para ver la licencia del proyecto', verbose_name='URL de licencia')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='portfolio', verbose_name='Imágen Destacada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.URLField(help_text='El sitio web donde se encuentra alojado el proyecto.', verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Ingrese el nombre del proyecto.', max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
