# Generated by Django 3.2 on 2021-04-24 05:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fsproject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gnu Compiler Colection', help_text='Ingrese el nombre del proyecto a mostrar en        el salón de la fama', max_length=60, verbose_name='Nombre')),
                ('icon', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='licenses', verbose_name='Icono del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto del salón de la fama',
                'verbose_name_plural': 'Proyectos del salón de la Fama',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gnu General Public License v2', help_text='Ingrese el nombre de la licencia a mostrar', max_length=60, verbose_name='Nombre')),
                ('verbatim', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Escriba aquí el texto corto o resumen de la licencia', verbose_name='Texto corto de la licencia')),
                ('license_link', models.URLField(default='https://gnu.org/', help_text='URL completa para ver la licencia del proyecto', verbose_name='URL de licencia')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.AlterField(
            model_name='fsproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
