# Generated by Django 3.2 on 2021-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210424_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsproject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='fsproject',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated_on',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización'),
        ),
    ]
