# Generated by Django 3.2 on 2021-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='Política de Privacidad', help_text='Ingrese el título para su política de privacidad', max_length=100, verbose_name='Título'),
        ),
    ]
