# Generated by Django 3.2 on 2021-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_privacypolicy_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Política de Privacidad', 'verbose_name_plural': 'Política de Privacidad'},
        ),
    ]
