# Generated by Django 3.2 on 2021-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210424_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes de dimensiones rectangulares.', upload_to='team', verbose_name='Foto del integrante')),
                ('name', models.CharField(default='', help_text='Ingrese el nombre del integrante del equipo', max_length=100, verbose_name='Nombre del Integrante del equipo')),
                ('position', models.CharField(default='', help_text='Ingrese en que ha contribuido o que posición dentro        de UpVent tiene el integrante.', max_length=100, verbose_name='Posición o contribución')),
                ('is_collab', models.BooleanField(default=False, help_text='Indicar si el miembro siendo registrado es un colaborador        externo, de no serlo se tomará como miembro de UpVent', verbose_name='¿Es un colaborador externo?')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
            },
        ),
    ]
