# Generated by Django 3.2 on 2021-04-27 01:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Se recomiendan imágenes cuadradas', upload_to='testimonials', verbose_name='Foto del cliente')),
                ('name', models.CharField(default='', help_text='Ingrese el nombre de la persona dando su testimonio.', max_length=100, unique=True, verbose_name='Nombre Completo')),
                ('testimonial', ckeditor_uploader.fields.RichTextUploadingField(help_text='Testimonio de la persona.', verbose_name='Testimonio')),
                ('workplace', models.CharField(help_text='Ingrese el puesto que desempeña la persona que da el        testimonio.', max_length=80, verbose_name='Lugar de Trabajo')),
                ('site', models.URLField(help_text='El sitio web donde se encuentra alojado el proyecto.', verbose_name='Sitio web')),
            ],
        ),
    ]
