# Generated by Django 3.2 on 2021-04-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
    ]
